// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_ring_create
SEXP cpp_ring_create(int n_channels, int capacity, std::string dtype, double memory_limit);
RcppExport SEXP _PhysioStream_cpp_ring_create(SEXP n_channelsSEXP, SEXP capacitySEXP, SEXP dtypeSEXP, SEXP memory_limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_channels(n_channelsSEXP);
    Rcpp::traits::input_parameter< int >::type capacity(capacitySEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< double >::type memory_limit(memory_limitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_create(n_channels, capacity, dtype, memory_limit));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_push
Rcpp::List cpp_ring_push(SEXP pointer, Rcpp::NumericMatrix samples, Rcpp::NumericVector timestamps);
RcppExport SEXP _PhysioStream_cpp_ring_push(SEXP pointerSEXP, SEXP samplesSEXP, SEXP timestampsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type timestamps(timestampsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_push(pointer, samples, timestamps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_pull
Rcpp::List cpp_ring_pull(SEXP pointer, int n);
RcppExport SEXP _PhysioStream_cpp_ring_pull(SEXP pointerSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_pull(pointer, n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_peek
Rcpp::List cpp_ring_peek(SEXP pointer, int n, std::string from);
RcppExport SEXP _PhysioStream_cpp_ring_peek(SEXP pointerSEXP, SEXP nSEXP, SEXP fromSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type from(fromSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_peek(pointer, n, from));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_reset
Rcpp::List cpp_ring_reset(SEXP pointer);
RcppExport SEXP _PhysioStream_cpp_ring_reset(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_reset(pointer));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_stats
Rcpp::List cpp_ring_stats(SEXP pointer);
RcppExport SEXP _PhysioStream_cpp_ring_stats(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_stats(pointer));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ring_finalize
void cpp_ring_finalize(SEXP pointer);
RcppExport SEXP _PhysioStream_cpp_ring_finalize(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    cpp_ring_finalize(pointer);
    return R_NilValue;
END_RCPP
}
// cpp_ring_stress
Rcpp::List cpp_ring_stress(int iterations, int capacity);
RcppExport SEXP _PhysioStream_cpp_ring_stress(SEXP iterationsSEXP, SEXP capacitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type capacity(capacitySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ring_stress(iterations, capacity));
    return rcpp_result_gen;
END_RCPP
}
// cpp_monotonic_ns
double cpp_monotonic_ns();
RcppExport SEXP _PhysioStream_cpp_monotonic_ns() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_monotonic_ns());
    return rcpp_result_gen;
END_RCPP
}
// cpp_pipeline_sos_rms
Rcpp::List cpp_pipeline_sos_rms(const Rcpp::NumericMatrix& samples, const Rcpp::NumericMatrix& sos, const Rcpp::NumericVector& zi_input, const Rcpp::NumericMatrix& buffer_input, const Rcpp::NumericVector& sums_input, int cursor, int filled);
RcppExport SEXP _PhysioStream_cpp_pipeline_sos_rms(SEXP samplesSEXP, SEXP sosSEXP, SEXP zi_inputSEXP, SEXP buffer_inputSEXP, SEXP sums_inputSEXP, SEXP cursorSEXP, SEXP filledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sos(sosSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type zi_input(zi_inputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type buffer_input(buffer_inputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sums_input(sums_inputSEXP);
    Rcpp::traits::input_parameter< int >::type cursor(cursorSEXP);
    Rcpp::traits::input_parameter< int >::type filled(filledSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pipeline_sos_rms(samples, sos, zi_input, buffer_input, sums_input, cursor, filled));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhysioStream_cpp_ring_create", (DL_FUNC) &_PhysioStream_cpp_ring_create, 4},
    {"_PhysioStream_cpp_ring_push", (DL_FUNC) &_PhysioStream_cpp_ring_push, 3},
    {"_PhysioStream_cpp_ring_pull", (DL_FUNC) &_PhysioStream_cpp_ring_pull, 2},
    {"_PhysioStream_cpp_ring_peek", (DL_FUNC) &_PhysioStream_cpp_ring_peek, 3},
    {"_PhysioStream_cpp_ring_reset", (DL_FUNC) &_PhysioStream_cpp_ring_reset, 1},
    {"_PhysioStream_cpp_ring_stats", (DL_FUNC) &_PhysioStream_cpp_ring_stats, 1},
    {"_PhysioStream_cpp_ring_finalize", (DL_FUNC) &_PhysioStream_cpp_ring_finalize, 1},
    {"_PhysioStream_cpp_ring_stress", (DL_FUNC) &_PhysioStream_cpp_ring_stress, 2},
    {"_PhysioStream_cpp_monotonic_ns", (DL_FUNC) &_PhysioStream_cpp_monotonic_ns, 0},
    {"_PhysioStream_cpp_pipeline_sos_rms", (DL_FUNC) &_PhysioStream_cpp_pipeline_sos_rms, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhysioStream(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
