# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ring_create <- function(n_channels, capacity, dtype, memory_limit) {
    .Call(`_PhysioStream_cpp_ring_create`, n_channels, capacity, dtype, memory_limit)
}

cpp_ring_push <- function(pointer, samples, timestamps) {
    .Call(`_PhysioStream_cpp_ring_push`, pointer, samples, timestamps)
}

cpp_ring_pull <- function(pointer, n) {
    .Call(`_PhysioStream_cpp_ring_pull`, pointer, n)
}

cpp_ring_peek <- function(pointer, n, from) {
    .Call(`_PhysioStream_cpp_ring_peek`, pointer, n, from)
}

cpp_ring_reset <- function(pointer) {
    .Call(`_PhysioStream_cpp_ring_reset`, pointer)
}

cpp_ring_stats <- function(pointer) {
    .Call(`_PhysioStream_cpp_ring_stats`, pointer)
}

cpp_ring_finalize <- function(pointer) {
    invisible(.Call(`_PhysioStream_cpp_ring_finalize`, pointer))
}

cpp_ring_stress <- function(iterations, capacity) {
    .Call(`_PhysioStream_cpp_ring_stress`, iterations, capacity)
}

cpp_monotonic_ns <- function() {
    .Call(`_PhysioStream_cpp_monotonic_ns`)
}

cpp_pipeline_sos_rms <- function(samples, sos, zi_input, buffer_input, sums_input, cursor, filled) {
    .Call(`_PhysioStream_cpp_pipeline_sos_rms`, samples, sos, zi_input, buffer_input, sums_input, cursor, filled)
}
